### ISSUE TITLE
[BUG] Incorrect Handling of Tasks with Same Start and Finish Times in lastRunFinishedTooLate() Method

### ISSUE THREAD

**Issue by nastoychev** [spatie/laravel-schedule-monitor#108]
**PHP Version**: PHP 8.2.14
**OS**: alpine3.18

Steps to reproduce the bug.
1. Insert data:
 - **DB: monitored_scheduled_tasks**

    ```
    INSERT INTO monitored_scheduled_tasks (id, name, type, cron_expression, timezone, ping_url, 
    last_started_at, last_finished_at, last_failed_at, last_skipped_at, registered_on_oh_dear_at, last_pinged_at, 
    grace_time_in_minutes, created_at, updated_at) VALUES (1, 'prune-health-check-logs', 'command', '0 0 * * *', 'UTC', null, 
    '2024-03-22 00:00:00', '2024-03-22 00:00:00', null, null, null, null, 5, '2024-03-21 09:55:08', '2024-03-21 09:55:08');
    ```

 - **DB: monitored_scheduled_task_log_items**
    ```
    INSERT INTO monitored_scheduled_task_log_items (id, monitored_scheduled_task_id, type, meta, 
    created_at, updated_at) VALUES (1, 1, 'starting', '{"memory": 33554432}', '2024-03-22 00:00:00', '2024-03-22 00:00:00');
    INSERT INTO monitored_scheduled_task_log_items (id, monitored_scheduled_task_id, type, meta, 
    created_at, updated_at) VALUES (2, 1, 'finished', '{"memory": 33554432, "output": null, "runtime": 0.37, "exit_code": 0}', '2024- 
   03-22 00:00:00', '2024-03-22 00:00:00');
    ```

2. `php artisan schedule-monitor:list`
 
![image](https://github.com/spatie/laravel-schedule-monitor/assets/41673191/a32bf259-b3a1-4590-8b51-1a144376476d)

**Comment by mathiasmoser** [comment]
I looked at the Method and i think the problem is caused by this line:

$expectedNextRunStart = $this->nextRunAt($lastFinishedAt->subSecond());

If the lastStartedAt and the lastFinishedAt are equal (because the task runs under a second) this line of code is not working. The question is - why the subSecond() is necessary - without it the code would work.

**Comment by mathiasmoser** [comment]
I have now created a PR to fix the problem:
https://github.com/spatie/laravel-schedule-monitor/pull/109
