### ISSUE TITLE
Ping endpoint not being called when tasks are run in the background

### ISSUE THREAD

**Issue by mattiasgeniar** [spatie/laravel-schedule-monitor#16]
With an active Oh Dear config, the following will only report the runs in the first 2 commands. The background task is never reported.

```php
    protected function schedule(Schedule $schedule)
    {
        $schedule->command('test:background --text 1')->everyMinute();

        $schedule->command('test:background --text 2')->everyMinute();

        $schedule->command('test:background --text 3')->everyMinute()->runInBackground();
    }
```

It may be because background tasks communicate back through a shared mutex, that doesn't send the same events?

**Comment by freekmurze** [comment]
This test seems to work: `it_works_correctly_when_a_task_is_run_in_the_background`. I'll try it out in a real app.

**Comment by freekmurze** [comment]
The package seems to work correctly.
