### ISSUE TITLE
log_items table filling up and not cleaning automatically?

### ISSUE THREAD

**Issue by sts-ryan-holton** [spatie/laravel-schedule-monitor#21]
Hi, I'm using a Laravel 7.x project and have several tasks set up and have this package installed, it's seemingly working great, with the exception that the `monitored_scheduled_task_log_items` items table has thousands of rows in it now from as little as a 2 week period it's got over 4,000 rows. I've seen https://github.com/spatie/laravel-schedule-monitor#cleaning-the-database and have this setup as follows:

```php
$schedule->command('schedule-monitor:sync')->dailyAt('04:56');
$schedule->command('schedule-monitor:clean')->daily();
```

How can I dump the contents of this table as I feel it's never going to empty automatically?

My commands array is as follows:

```php
protected $commands = [
        'App\Console\Commands\CheckDomainExpiry',
        'App\Console\Commands\EmailDomainAlerts',
        'App\Console\Commands\DatabaseCleanup'
    ];
```

**Comment by freekmurze** [comment]
Feel free to implement your own cleaning procedure.
