### ISSUE TITLE
Add support for Kernel's scheduleTimezone()

### ISSUE THREAD

**Issue by mattiasgeniar** [spatie/laravel-schedule-monitor#28]
Laravel allows you to set a custom timezone for Kernel commands: https://laravel.com/docs/8.x/scheduling#timezones

It appears right now, the package doesn't take this into account when creating schedule monitors towards Oh Dear.

> If you are assigning the same timezone to all of your scheduled tasks, you may wish to define a `scheduleTimezone` method in your `app/Console/Kernel.php` file. This method should return the default timezone that should be assigned to all scheduled tasks:

```php
/**
 * Get the timezone that should be used by default for scheduled events.
 *
 * @return \DateTimeZone|string|null
 */
protected function scheduleTimezone()
{
    return 'America/Chicago';
}
```

**Comment by freekmurze** [comment]
I've done some testing and it seems like we already support this.

<img width="1639" alt="image" src="https://user-images.githubusercontent.com/483853/96491335-61a0c600-1242-11eb-9278-a97c8d89bc87.png">

The stored `timezone` on `MonitoredScheduledTask` will be sent to Oh Dear.
