### ISSUE TITLE
Errors after upgrading Laravel 7 -> Laravel 8 timezone error!

### ISSUE THREAD

**Issue by sts-ryan-holton** [spatie/laravel-schedule-monitor#33]
Hi, I was previously using Laravel 7 and had the schedule monitor tables and log items with data in them. I've recently upgraded to Laravel 8 and have also updated this package. When tying to run `php artisan migrate` a bunch of errors appear telling me that the table exists (presumably because something has changed). So I've deleted the `schedule-monitor.php` config file, and re-published it.

Now whenever I try to run a `php artisan migrate` on my production environment (which has the old db schema), it won't migrate correctly and throws errors...

```
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'monitored_scheduled_tasks' already exists (SQL: create table `monitored_scheduled_tasks` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `type` varchar(255) null, `cron_expression` varchar(255) not null, `timezone` varchar(255) null, `ping_url` varchar(255) null, `last_started_at` datetime null, `last_finished_at` datetime null, `last_failed_at` datetime null, `last_skipped_at` datetime null, `registered_on_oh_dear_at` datetime null, `last_pinged_at` datetime null, `grace_time_in_minutes` int not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')
```

I've added a new task that needs monitoring, and it won't add to the monitors list because of a timezone error?

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'timezone' in 'field list' (SQL: update `monitored_scheduled_tasks` set `timezone` = UTC, `monitored_scheduled_tasks`.`updated_at` = 2020-11-17 12:10:59 where `id` = 1)
```

Which is why a `migrate:fresh` works for me locally. However, **in production I can't do this because it would dump all of my other tables.** I tried a `migrate:refresh` specifying the path, and it returns the same errors, see attached.

Please fix or advise on getting that timezone error fixed ASAP!

![Screenshot 2020-11-17 at 12 04 32](https://user-images.githubusercontent.com/25177538/99388910-2f7c9580-28ce-11eb-9fd5-78935cc59353.png)

![Screenshot 2020-11-17 at 12 12 48](https://user-images.githubusercontent.com/25177538/99388941-3b685780-28ce-11eb-964b-4a1364f86e43.png)

**UPDATE**

With some faffing around, I've got past the issue of migrating the tables by forcefully deleting the migrations, and those two tables and re-creating them. They've been successfully migrated, but the timezone error persists...

**Comment by Quiss** [comment]
got the same error

**Comment by freekmurze** [comment]
I can't seem to reproduce this, and all tests are passing. Feel free to PR a failing test for me to look at.
