### ISSUE TITLE
`Invalid datetime format` exception when creating log items

### ISSUE THREAD

**Issue by SamuelNitsche** [spatie/laravel-schedule-monitor#39]
Last night sentry informed me about an error in my application which occurred in this package. I took a look at the exception but I am not sure what the problem here is. This is the full exception message.

```
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2021-03-28 02:59:01' for column `xxx`.`monitored_scheduled_task_log_items`.`updated_at` at row 1 (SQL: insert into `monitored_scheduled_task_log_items` (`type`, `monitored_scheduled_task_id`, `updated_at`, `created_at`) values (starting, 1, 2021-03-28 02:59:01, 2021-03-28 02:59:01))
```

I don't know why the given value is an invalid datetime format.

Do you guys have an idea what the issue is here?

**Comment by freekmurze** [comment]
That time doesn't exist due to the hour jump in daylight savings time
