### ISSUE TITLE
vendor:publish with tag option fails

### ISSUE THREAD

**Issue by karunkshrestha** [spatie/laravel-schedule-monitor#60]
When running
`php artisan vendor:publish --provider="Spatie\ScheduleMonitor\ScheduleMonitorServiceProvider" --tag="migrations"`

**Output**
`Unable to locate publishable resources.
Publishing complete.`

But if I leave the tag option out, it publishes (both migration and config)
`php artisan vendor:publish --provider="Spatie\ScheduleMonitor\ScheduleMonitorServiceProvider"`

**Output**
`Copied File [\vendor\spatie\laravel-schedule-monitor\config\schedule-monitor.php] To [\config\schedule-monitor.php]
Copied File [\vendor\spatie\laravel-schedule-monitor\database\migrations\create_schedule_monitor_tables.php.stub] To [\database\migrations\2021_08_20_141405_create_schedule_monitor_tables.php]
Publishing complete.`

Is this something to do with how spatie/laravel-package-tools deals with the tag option?

Thanks

**Comment by freekmurze** [comment]
I've fixed it in the readme.
