### ISSUE TITLE
Store the command output in log items or add custom meta data

### ISSUE THREAD

**Issue by michellaurent** [spatie/laravel-schedule-monitor#8]
It would be nice if, for each execution of a task, the output of this task is stored in the log items table.

It maybe could also be useful to be able to add custom meta data within the task like the numbers of emails sent for a task that sends trial ending reminders for example.

**Comment by freekmurze** [comment]
I'd like to keep this package as light as possible. I'm open for a PR that adds events to the package, that allows you to add the described behaviour to your own app.
