### ISSUE TITLE
Creation of dynamic property Illuminate\Console\Scheduling\Event::$doNotMonitor is deprecated

### ISSUE THREAD

**Issue by martio** [spatie/laravel-schedule-monitor#87]
The new version of the Laravel framework, v10.11.0, brings the following warning:

```
WARNING: Creation of dynamic property Illuminate\Console\Scheduling\Event::$doNotMonitor is deprecated in /var/www/html/vendor/spatie/laravel-schedule-monitor/src/ScheduleMonitorServiceProvider.php on line 117  
```

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this.

**Comment by martio** [comment]
The Laravel Team needs to make a correction and add the #[AllowDynamicProperties] attribute to the Illuminate\Console\Scheduling\Event class.

Deprecated dynamic properties in PHP 8.2:

`ScheduleMonitorServiceProvider`

```
        SchedulerEvent::macro('doNotMonitor', function () {
            $this->doNotMonitor = true;

            return $this;
        });
```

**Comment by freekmurze** [comment]
Fixed in the latest release.
