### ISSUE TITLE
Creation of dynamic property $graceTimeInMinutes is deprecated

### ISSUE THREAD

**Issue by raray** [spatie/laravel-schedule-monitor#93]
I'm getting thousands of these messages since upgrading to PHP8.2:

```
Creation of dynamic property Illuminate\Console\Scheduling\Event::$graceTimeInMinutes is deprecated in ...
```

I'm sorry that I don't really have much to offer other than our usage which is:

```
protected function schedule(Schedule $schedule)
    {
        $schedule->command('sendEmails')->everyMinute()->graceTimeInMinutes(10);
        $schedule->command('sendPartnerEmails')->everyMinute()->graceTimeInMinutes(45);
    }
```

**Comment by wivaku** [comment]
Same for e.g.
```
Creation of dynamic property Illuminate\Console\Scheduling\Event::$monitorName is deprecated in /Users/winfred/code/npo/npo-rcrs-datamigration-tooling/vendor/spatie/laravel-schedule-monitor/src/ScheduleMonitorServiceProvider.php on line 105
```

**Comment by wivaku** [comment]
Same for e.g.
```
Creation of dynamic property Illuminate\Console\Scheduling\Event::$monitorName is deprecated in .../vendor/spatie/laravel-schedule-monitor/src/ScheduleMonitorServiceProvider.php on line 105
```

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this.

**Comment by akiyamaSM** [comment]
You need to upgrade the Laravel version to support 8.2. on my side the package worked for me under PHP 8.2.

**Comment by codetroll** [comment]
I upgraded to 8.2 - that didn't help. Besides - the requirement for laravel 10 states PHP 8.1/8.2 so some kind of workaround should probably be made for 8.1

**Comment by heikokrebs** [comment]
I still get this errors, despite the fix in #98 after upgrading to php 8.2
I dont get why, since this properties are now declared at the class 🤔

`Creation of dynamic property Illuminate\Console\Scheduling\Event::$monitorName is deprecated in …vendor/spatie/laravel-schedule-monitor/src/ScheduleMonitorServiceProvider.php on line 113`

`Creation of dynamic property Illuminate\Console\Scheduling\CallbackEvent::$monitorName is deprecated in …vendor/spatie/laravel-schedule-monitor/src/ScheduleMonitorServiceProvider.php on line 113`

**Comment by exophunk** [comment]
For me the same deprecation errors also still show up. The issue seems not to be fixed and maybe needs to be reopened? Maybe there is another mechanism how to add grace time or monitor name?

**Comment by heikokrebs** [comment]
@freekmurze do you have the opportunity to take another look here?

**Comment by freekmurze** [comment]
Currently short on time, if it's urgent, please submit a PR 👍

**Comment by heikokrebs** [comment]
@freekmurze unfortunately, i have no idea what a fix could look like. But I would like to use Oh Dear in this way with our account. Any idea/direction?
